language: c

sudo: false

cache:
  directories:
    - ~/.cabal/packages
    - ~/.cabal/store

env:
  global:
    # To avoid re-compilation it is important to use exactly the same
    # configuration for all steps.
    - CABAL_CONFIG="--enable-tests --enable-benchmarks --flags=dev"

matrix:
  include:
    - env: CABALVER=3.0 GHCVER=8.6.5
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.6.5], sources: [hvr-ghc]}}
    - env: CABALVER=3.0 GHCVER=8.8.3
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.8.3], sources: [hvr-ghc]}}
    - env: CABALVER=3.0 GHCVER=8.10.1
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.10.1], sources: [hvr-ghc]}}

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  - cabal --version
  - ghc --version
  - travis_retry cabal new-update

script:
  - cabal format
  - pushd megaparsec-tests && cabal format && popd
  - git diff --exit-code --color=always
  - cabal new-build all $CABAL_CONFIG
  - cabal new-test all $CABAL_CONFIG
  - cabal new-haddock megaparsec $CABAL_CONFIG
  - cabal new-haddock megaparsec-tests $CABAL_CONFIG
  - cabal new-sdist
  - pushd megaparsec-tests && cabal new-sdist && popd

notifications:
  email: false
