language: c

sudo: false

cache:
  directories:
    - ~/.cabal/packages
    - ~/.cabal/store

matrix:
  include:
    - env: CABALVER=2.4 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-2.4,ghc-7.10.3],sources: [hvr-ghc]}}
    - env: CABALVER=2.4 GHCVER=8.0.2
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.0.2], sources: [hvr-ghc]}}
    - env: CABALVER=2.4 GHCVER=8.2.2
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.2.2], sources: [hvr-ghc]}}
    - env: CABALVER=2.4 GHCVER=8.4.4
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.4.4], sources: [hvr-ghc]}}
    - env: CABALVER=2.4 GHCVER=8.6.2
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.6.2], sources: [hvr-ghc]}}

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  - cabal --version
  - ghc --version
  - travis_retry cabal update

script:
  - cabal new-build --enable-tests --enable-benchmarks --flags=dev
  - cabal new-test
  - cabal new-haddock
  - cabal sdist

notifications:
  email: false
