language: c

sudo: false

cache:
  directories:
    - ~/.cabal/packages
    - ~/.cabal/store

matrix:
  include:
    - env: CABALVER=3.0 GHCVER=8.4.4
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.4.4], sources: [hvr-ghc]}}
    - env: CABALVER=3.0 GHCVER=8.6.5
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.6.5], sources: [hvr-ghc]}}
    - env: CABALVER=3.0 GHCVER=8.8.3
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.8.3], sources: [hvr-ghc]}}

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  - cabal --version
  - ghc --version
  - travis_retry cabal new-update

script:
  - cabal new-build all --enable-tests --enable-benchmarks --flags=dev
  - cabal new-test all --enable-tests --enable-benchmarks --flags=dev
  - cabal new-haddock megaparsec
  - cabal new-haddock megaparsec-tests
  - cabal new-sdist
  - cd megaparsec-tests && cabal new-sdist

notifications:
  email: false
